name: lab1_iris
channels: 
- defaults
- conda-forge
dependencies:
- python==3.10.13
- numpy
- pandas
- joblib
- scikit-learn==1.1.1
- seaborn
- dataframe_image
- modal
- gradio
- pip
- twofish
# You also need to install "hopsworks" through "pip install hopsworks"
